### Authorization by token, part 1. Retrieve and save token.
POST http://127.0.0.1:8000/api/v1.0/event/create/
Content-Type: application/json

{
  "event_type": "Coffeebrake_2",
  "info":
    {
      "all_info": "text"
    },
  "timestamp": "2023-02-06 13:45:05"
}

