# Generated by Django 4.1.6 on 2023-02-04 11:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Type of the event',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('info', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 2, 4, 13, 36, 9, 559973))),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type', to='event_manager.eventtype')),
                ('user', models.ForeignKey(on_delete=models.SET('User was delete'), related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'ordering': ['event_type', 'timestamp'],
            },
        ),
    ]
