# Generated by Django 4.1.6 on 2023-02-07 10:49

import datetime
from django.db import migrations, models
import event_manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created_at',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ('id',), 'verbose_name': 'Type of the event', 'verbose_name_plural': 'Types of events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 10, 48, 44, 693706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(validators=[event_manager.validators.DateValidator.timestamp_validator]),
        ),
    ]
